# Source: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

name: Build and push image to Docker Hub

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build the image
        run: |
          docker buildx build --push \
            --tag trmnl/trmnlp:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
